Mobile menu
Rudy-Menekam/Portfolio-1 pull request #12
Opened 2023-01-04 12:57 UTC by Rudy-Menekam

In this PR, I did the following

1. Set HTML CSS JS linters
2. Add a mobile menu section in the HTML file
3. Select the menu and close icon and run open menu and close functions

2023-01-04 15:33 UTC, gemmen29 requested changes
Hi @Rudy-Menekam, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights 💯 
- No linters errors ✔️ 
- Descriptive pull request ✔️ 
- Descriptive commit messages ✔️ 

![](https://media.giphy.com/media/tKyrc0NTlEcGWdThp4/giphy.gif)

## Required Changes ♻️
- [ ] Please be sure to use the linters of Javascript in your project that exists [here](https://github.com/microverseinc/linters-config/tree/master/javascript). This will be the linters template that you will use for all Javascript projects.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-04 15:36 UTC, Rudy-Menekam commented
Hi @gemmen29, thanks for reviewing my work. but please I don't understand the change you want me to add, I have added the javascript linter already

2023-01-04 17:10 UTC, joskalenda requested changes
| STATUS: REQUIRED CHANGES ♻️  |
|--------------------------------|
| Hi @Rudy-Menekam , |
|Great work on making the changes requested by a previous reviewer 👏, You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet. |
| <img src="https://media4.giphy.com/media/ReyD4OdRiHeLDCRaEP/giphy.gif"/> |

## Highlights

- [ ].. ✅ Good design
- [ ].. ✅ Green linters but you need to add JS one

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

-------
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me(@joskalenda) in your question so I can receive the notification.

> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-04 17:10 UTC, joskalenda commented on .eslintrc.json
> +    },
- [ ] Okay, cross your fingers and read this comment carefully, it will help you understand why the previous reviewer said you did not install the js linter,

| image 1 | image 2 |
|---------|---------|
| <img width="1119" alt="2" src="https://user-images.githubusercontent.com/77843050/210604738-f5012519-27c7-4bbf-ab3e-0b1a431b27df.png"> | <img width="1106" alt="4" src="https://user-images.githubusercontent.com/77843050/210605339-ee7d7756-4749-4cfa-aa24-37e0523fa0d5.png"> |

- Better you see what we mean with some examples, above are 4 images (2 left and 2 right), the ones bordered in red are the correct JS linter configured in the project, on the right, not bordered are your files, and your linter checks, see the differences? 
- Now, image 1 is a screenshot of the linter.yml file, we can see the eslint config in red that is not present in your linter.yml file, and image 2 is a screenshot of the GitHub checks ✅, we can see the `eslint` bordered in red missing in your checks, see? what I think is you have added the eslintrc.json but this is not all, you should have run the command to install it afterward,.so if you did it already and the linter was not successfully installed,   please start over following these steps [here](https://github.com/microverseinc/linters-config/tree/master/javascript)

2023-01-04 17:10 UTC, joskalenda commented on index.html
> +          <img class="mos-0" src="images/image_geometry_menu_2.svg" alt="image_geometry_menu_2">
- [ ] [ OPTIONAL ] You have done fine on creating this nav menu, but please try to fix this broken design as you still need to work o the next submission, check this out 👀 
- The X icon font weight is a bit more on the original design, 
- When the user scrolls your page, the nav menu is not fixed, it scrolls accordingly which is not a good way to present things, please make a few touches on that too.

<img width="664" alt="1" src="https://user-images.githubusercontent.com/77843050/210610908-b313ca15-9936-4089-97e2-5fc47a2acf0d.png">

![5](https://user-images.githubusercontent.com/77843050/210610948-ee163433-9afb-4882-8b89-4e63560d01cd.gif)

2023-01-05 09:34 UTC, OyePriscilla approved these changes
Hi @Rudy-Menekam 👍 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![200](https://user-images.githubusercontent.com/103386183/196424328-985f6e98-f7c6-4cf9-bafe-158436f70560.gif)

## Highlights
Linters check passed ✔️ 
Good commit messages ✔️ 
GitHub flow observed 😄 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-05 09:51 UTC, merged